### ISSUE TITLE
Update Kibiter to the latest release of Kibana 6.1 series (6.1.4)

### ISSUE THREAD

**Issue by sduenas** [grimoirelab/kibiter#103]
Kibiter is using Kibana 6.1.0. The latest version is 6.1.4. This update will close some bugs and add some important features as the Kibana API for saving objects.

**Comment by dlumbrer** [comment]
The update is ready, we have our 4 branches as usual:

- integration-6.1.4
- integration-6.1.4-optimized
- integration-6.1.4-secured
- integration-6.1.4-communitty

The community release is available in GitHub: https://github.com/chaoss/grimoirelab-kibiter/releases/tag/community-v6.1.4-1

**Comment by dlumbrer** [comment]
The images are ready in docker-hub:

- default-v6.1.4-1 (from integration-6.1.4)
- optimized-v6.1.4-1 (from integration-6.1.4-optimized)
- secured-v6.1.4-1 (from integration-6.1.4-secured)
- community-v6.1.4-1 (from integration-6.1.4-community)
