### ISSUE TITLE
Bitergia logo does not load

### ISSUE THREAD

**Issue by sduenas** [grimoirelab/kibiter#144]
This bug is related with the code in `secured-v6.8.6-2` tag and others related to it.

When the env variable `LOGIN_BRANDIMAGE` is not set, the container should load the Bitergia logo (see it in [here](https://github.com/chaoss/grimoirelab-kibiter/blob/secured-v6.8.6-2/docker/docker_entrypoint.sh#L48)).

The [link](https://bitergia.com/assets/img/bitergia_logo-907x227.png) to the image is down. Due to this and empty image is loaded when loading the login page.

![imagen](https://user-images.githubusercontent.com/833352/79472276-ee549800-8003-11ea-8f8f-a73cb12a59b0.png)

**Comment by dlumbrer** [comment]
As @sduenas said, this error appears when the link to the asset in the web-page is down. In order to solve this, we added the image in the repository in order to have always the image there.

I prepared the PR (#145), please @sduenas, check it when you can

**Comment by jsmanrique** [comment]
One small comment. I think Kibiter should have 2 look & feels or skins (including this logo):
* one for GrimoireLab (as part of the GrimoireLab toolkit)
* one for Bitergia Analytics (as part of the Bitergia Analytics platform)

**Comment by dlumbrer** [comment]
> One small comment. I think Kibiter should have 2 look & feels or skins (including this logo):
> 
>     * one for GrimoireLab (as part of the GrimoireLab toolkit)
> 
>     * one for Bitergia Analytics (as part of the Bitergia Analytics platform)

It has two versions indeed, as we have integration-6.8.6 (Bitergia) and integration-community-6.8.6 (GrimoireLab). Moreover, in the releases tab, we have the binaries of each version there (ready to download and launch) :smile: .

This logo is for the login form, the community version does not have the security plugin installed, that's the reason for doing the PR just on one branch.

**Comment by dlumbrer** [comment]
Image created and issue solved, closing!
