### ISSUE TITLE
Update Kibiter README.md according to its particularities

### ISSUE THREAD

**Issue by jsmanrique** [grimoirelab/kibiter#68]
Since this is a fork of Kibana, it's using its same README.md file, that could make sense. But there seems to be some differences about how it is run, specially as a container. And, since the README.md file is used in DockerHub as reference, that information is lost:
https://hub.docker.com/r/bitergia/kibiter/

For example, the environment variables meaning is missed. Things like `PROJECT_NAME`, what do they mean?

**Comment by dlumbrer** [comment]
The README.md of the `integration` branches are updated. Closing!
