### ISSUE TITLE
Kibiter Compaitability Error

### ISSUE THREAD

**Issue by Avfdo1994** [grimoirelab/kibiter#69]
**Kibana version**:6.1.0

**Elasticsearch version**:6.1.0

**Server OS version**:Ubuntu 16.04

**Browser version**:Firefox 

**Browser OS version**:Ubuntu 16.04

**Original install method (e.g. download page, yum, from source, etc.)**:download page 

**Description of the problem including expected versus actual behavior**:
Expected: Kibana and Elasticsearch( Both Same Versions) to run without any issues 
Actual: 
log   [04:32:22.507] [warning] You're running Kibana 6.1.0-1 with some different versions of Elasticsearch. Update Kibana or Elasticsearch to the same version to prevent compatibility issues: v6.1.0 @ 127.0.0.1:9200 (127.0.0.1)

**Steps to reproduce**:
 1. Initiate ElasticSearch
 2. Initiate Kibana
 3.

**Errors in browser console (if relevant)**: Unable to save when dashboard is up and running 

**Provide logs and/or server output (if relevant)**:

**Describe the feature**:

**Comment by acs** [comment]
This is just a waning. No issues must be derived from this warning.

Thanks you for the report!
