### ISSUE TITLE
Unable to save dashboard

### ISSUE THREAD

**Issue by Avfdo1994** [grimoirelab/kibiter#70]
**Kibana version**: 6.1.0

**Elasticsearch version**: 6.1.0

**Server OS version**: Ubuntu 16.04

**Browser version**: Firefox 

**Browser OS version**: Ubuntu 16.04

**Original install method (e.g. download page, yum, from source, etc.)**: source 

**Description of the problem including expected versus actual behavior**:
Expected: Dashboard to save successfully after changes 
Actual: Dashboard produces an error when trying to save changes 

**Steps to reproduce**:
 1. Make changes to dashboard 
 2. Click on Save 
 3. Produces Error (Dashboard: Scope not defined)

**Errors in browser console (if relevant)**:
![image](https://user-images.githubusercontent.com/36190328/38248351-b38a4776-3765-11e8-849a-8dab324c2124.png)

**Provide logs and/or server output (if relevant)**:

**Describe the feature**:

**Comment by Avfdo1994** [comment]
This is just a bug. The Dashboard gets saved but an error like this is always produced

**Comment by dlumbrer** [comment]
This problem was solved in the next releases of 6.1.0.

Sorry for the late notice.
