### ISSUE TITLE
Bitergia branding related work should be not part of chaoss/grimoirelab Kibiter branding

### ISSUE THREAD

**Issue by jsmanrique** [grimoirelab/kibiter#86]
I've seen several PRs done to have Bitergia branding in GrimoireLab Kibiter. These must not be part of GrimoireLab master branding but Bitergia branch, fork or whatever.

Potential related PRs:
https://github.com/chaoss/grimoirelab-kibiter/pull/81
https://github.com/chaoss/grimoirelab-kibiter/pull/82
https://github.com/chaoss/grimoirelab-kibiter/pull/84
https://github.com/chaoss/grimoirelab-kibiter/pull/85

**Comment by acs** [comment]
Probably we must have two branches:

* branding-grimoirelab
* branding-bitergia

A decision should be taken.

**Comment by acs** [comment]
I am working in the multibranch approach for the branding, generating different kibiter docker images, in CROSSMINER project. If you like this approach, I could help in applying them to GrimoireLab Kibiter (we used this approach also for the Kibiter used in Cauldron).

**Comment by dlumbrer** [comment]
This issue is fixed, we have now two images of kibiter each one with different branding (Community and Bitergia)
